name: Deploy to AWS Frontend Peach

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WAWCD_URL: https://wawcd.com/
      STRAPI_BE_URL_SERVER: https://strapi.wawcd.com
      NEXT_PUBLIC_STRAPI_BE_URL_CLIENT: https://strapi.wawcd.com
      STRAPI_ACCESS_TOKEN: ${{ secrets.STRAPI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build and test NextJS Frontend
        run: |
          npm install
          npm run build

  deploy-blueberry:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get SSH key and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_AWS_MASTER_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy to wawcd-fe-blueberry
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_AWS_USER }}@${{ secrets.SSH_HOST_FE_BLUEBERRY }} "cd ~/wawcd-website && git fetch origin && git reset origin/main --hard && ./deploy.sh prod"

  deploy-strawberry:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get SSH key and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_AWS_MASTER_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy to wawcd-fe-strawberry
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_AWS_USER }}@${{ secrets.SSH_HOST_FE_STRAWBERRY }} "cd ~/wawcd-website && git fetch origin && git reset origin/main --hard && ./deploy.sh prod"
